AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.6

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 400

Style/EmptyCaseCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/WordArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: false

