version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-buster-node
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_DB: codelog_test
          POSTGRES_USER: codelog
          POSTGRES_PASSWORD: codelog
    parallelism: 1
    environment:
      RAILS_ENV: test
      PGHOST: 127.0.0.1
      PGUSER: codelog
      PGPASSWORD: codelog
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-v1-{{ checksum "Gemfile.lock" }}
            - bundler-v1-
      - run: gem install bundler:2.1.4

      - run: bundle install --clean --path vendor/bundle

      - save_cache:
          key: bundler-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rake db:create db:schema:load db:seed --trace
      - run: bin/rails test
      - store_artifacts:
          path: coverage
